# Generated by Django 2.2 on 2019-04-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys19', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='is_updated',
        ),
    ]
