# Generated by Django 2.2 on 2019-04-13 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys19', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='management_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='surveys19.ManagementType', verbose_name='Management Type'),
            preserve_default=False,
        ),
    ]
