# Generated by Django 2.2 on 2019-04-10 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys19', '0002_remove_survey_is_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmlocation',
            options={'ordering': ('id', 'code'), 'verbose_name': 'FarmLocation', 'verbose_name_plural': 'FarmLocation'},
        ),
    ]
