# Generated by Django 2.2 on 2019-04-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys19', '0002_product_management_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerworkday',
            name='max_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Max Day'),
        ),
        migrations.AddField(
            model_name='farmerworkday',
            name='min_day',
            field=models.IntegerField(blank=True, null=True, verbose_name='Min Day'),
        ),
    ]
