# Generated by Django 2.2 on 2019-04-17 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys19', '0003_auto_20190414_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id', 'code'), 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
    ]
