# Generated by Django 2.2.1 on 2019-05-07 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys19', '0008_auto_20190507_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys19.Unit', verbose_name='Unit Product'),
        ),
    ]
