# Generated by Django 2.2 on 2019-05-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys19', '0008_auto_20190507_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderfile',
            name='delete_exist',
            field=models.BooleanField(default=False),
        ),
    ]
