from django.conf.urls import url

from .views import (
    SurveyListAPIView,
    SurveyUpdateAPIView,

    # Serializer Singleton
    ContentTypeSingletonListAPIView,
    SurveySingletonListAPIView,
    ShortTermHireSingletonListAPIView,
    LongTermHireSingletonListAPIView,
    NumberWorkersSingletonListAPIView,
    ShortTermLackSingletonListAPIView,
    LongTermLackSingletonListAPIView,
    NoSalaryHireSingletonListAPIView,
    SubsidySingletonListAPIView,
    RefuseSingletonListAPIView,
    PopulationSingletonListAPIView,
    PopulationAgeSingletonListAPIView,
    CropMarketingSingletonListAPIView,
    LivestockMarketingSingletonListAPIView,
    UnitSingletonListAPIView,
    ProductSingletonListAPIView,
    BusinessSingletonListAPIView,
    LandTypeSingletonListAPIView,
    LandAreaSingletonListAPIView,
    PhoneSingletonListAPIView,
    AddressMatchSingletonListAPIView,
    AnnualIncomeSingletonListAPIView,
    AgeScopeSingletonListAPIView,
    WorkTypeSingletonListAPIView,
    RefuseReasonSingletonListAPIView,
    FarmerWorkDaySingletonListAPIView,
    OtherFarmWorkSingletonListAPIView,
    RelationshipSingletonListAPIView,
    EducationLevelSingletonListAPIView,
    LifeStyleSingletonListAPIView,
    GenderSingletonListAPIView,
    LossSingletonListAPIView,
    FacilitySingletonListAPIView,
    ProductTypeSingletonListAPIView,
    ContractSingletonListAPIView,
    ManagementTypeSingletonListAPIView,
    FarmRelatedBusinessSingletonListAPIView,
    LandStatusSingletonListAPIView,
    LackSingletonListAPIView,
    IncomeRangeSingletonListAPIView,
    MarketTypeSingletonListAPIView,
    MonthSingletonListAPIView,
)

urlpatterns = [
    url(r'^$', SurveyListAPIView.as_view(), name='list'),
    url(r'^update/$', SurveyUpdateAPIView.as_view(), name='update'),

    # Serializer Singleton
    url(r'^survey/$', SurveySingletonListAPIView.as_view(), name='list_singleton_survey'),
    url(r'^contenttype/$', ContentTypeSingletonListAPIView.as_view(), name='list_singleton_contenttype'),
    url(r'^shorttermhire/$', ShortTermHireSingletonListAPIView.as_view(), name='list_singleton_shorttermhire'),
    url(r'^longtermhire/$', LongTermHireSingletonListAPIView.as_view(), name='list_singleton_longtermhire'),
    url(r'^numberworkers/$', NumberWorkersSingletonListAPIView.as_view(), name='list_singleton_numberworkers'),
    url(r'^shorttermlack/$', ShortTermLackSingletonListAPIView.as_view(), name='list_singleton_shorttermlack'),
    url(r'^longtermlack/$', LongTermLackSingletonListAPIView.as_view(), name='list_singleton_longtermlack'),
    url(r'^nosalaryhire/$', NoSalaryHireSingletonListAPIView.as_view(), name='list_singleton_nosalaryhire'),
    url(r'^subsidy/$', SubsidySingletonListAPIView.as_view(), name='list_singleton_subsidy'),
    url(r'^refuse/$', RefuseSingletonListAPIView.as_view(), name='list_singleton_refuse'),
    url(r'^population/$', PopulationSingletonListAPIView.as_view(), name='list_singleton_population'),
    url(r'^populationage/$', PopulationAgeSingletonListAPIView.as_view(), name='list_singleton_populationage'),
    url(r'^cropmarketing/$', CropMarketingSingletonListAPIView.as_view(), name='list_singleton_cropmarketing'),
    url(r'^livestockmarketing/$', LivestockMarketingSingletonListAPIView.as_view(), name='list_singleton_livestockmarketing'),
    url(r'^unit/$', UnitSingletonListAPIView.as_view(), name='list_singleton_unit'),
    url(r'^product/$', ProductSingletonListAPIView.as_view(), name='list_singleton_product'),
    url(r'^business/$', BusinessSingletonListAPIView.as_view(), name='list_singleton_business'),
    url(r'^landtype/$', LandTypeSingletonListAPIView.as_view(), name='list_singleton_landtype'),
    url(r'^landarea/$', LandAreaSingletonListAPIView.as_view(), name='list_singleton_landarea'),
    url(r'^phone/$', PhoneSingletonListAPIView.as_view(), name='list_singleton_phone'),
    url(r'^addressmatch/$', AddressMatchSingletonListAPIView.as_view(), name='list_singleton_addressmatch'),
    url(r'^annualincome/$', AnnualIncomeSingletonListAPIView.as_view(), name='list_singleton_annualincome'),

    # Serializer Singleton No Pagination
    url(r'^agescope/$', AgeScopeSingletonListAPIView.as_view(), name='list_singleton_agescope'),
    url(r'^worktype/$', WorkTypeSingletonListAPIView.as_view(), name='list_singleton_worktype'),
    url(r'^refusereason/$', RefuseReasonSingletonListAPIView.as_view(), name='list_singleton_refusereason'),
    url(r'^farmerworkday/$', FarmerWorkDaySingletonListAPIView.as_view(), name='list_singleton_farmerworkday'),
    url(r'^otherfarmwork/$', OtherFarmWorkSingletonListAPIView.as_view(), name='list_singleton_otherfarmwork'),
    url(r'^relationship/$', RelationshipSingletonListAPIView.as_view(), name='list_singleton_relationship'),
    url(r'^educationlevel/$', EducationLevelSingletonListAPIView.as_view(), name='list_singleton_educationlevel'),
    url(r'^lifestyle/$', LifeStyleSingletonListAPIView.as_view(), name='list_singleton_lifestyle'),
    url(r'^gender/$', GenderSingletonListAPIView.as_view(), name='list_singleton_gender'),
    url(r'^loss/$', LossSingletonListAPIView.as_view(), name='list_singleton_loss'),
    url(r'^facility/$', FacilitySingletonListAPIView.as_view(), name='list_singleton_facility'),
    url(r'^producttype/$', ProductTypeSingletonListAPIView.as_view(), name='list_singleton_producttype'),
    url(r'^contract/$', ContractSingletonListAPIView.as_view(), name='list_singleton_contract'),
    url(r'^managementtype/$', ManagementTypeSingletonListAPIView.as_view(), name='list_singleton_managementtype'),
    url(r'^farmrelatedbusiness/$', FarmRelatedBusinessSingletonListAPIView.as_view(), name='list_singleton_farmrelatedbusiness'),
    url(r'^landstatus/$', LandStatusSingletonListAPIView.as_view(), name='list_singleton_landstatus'),
    url(r'^lack/$', LackSingletonListAPIView.as_view(), name='list_singleton_lack'),
    url(r'^incomerange/$', IncomeRangeSingletonListAPIView.as_view(), name='list_singleton_incomerange'),
    url(r'^markettype/$', MarketTypeSingletonListAPIView.as_view(), name='list_singleton_markettype'),
    url(r'^month/$', MonthSingletonListAPIView.as_view(), name='list_singleton_month'),
]
