# Generated by Django 2.1.7 on 2019-03-25 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('initial_errors', models.IntegerField(blank=True, null=True, verbose_name='Initialed Error Count')),
                ('current_errors', models.IntegerField(blank=True, null=True, verbose_name='Current Error Count')),
                ('update_datetime', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('content_type', models.ForeignKey(limit_choices_to=(models.Q(('app_label', 'surveys18'), ('model', 'survey')), models.Q(('app_label', 'surveys19'), ('model', 'survey'))), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'ReviewLog',
                'verbose_name_plural': 'ReviewLogs',
            },
        ),
    ]
