# Generated by Django 2.2.10 on 2020-04-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20200412_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlog',
            old_name='update_datetime',
            new_name='update_time',
        ),
    ]
