# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('django_db_logger', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewLog',
            fields=[
                ('statuslog_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='django_db_logger.StatusLog')),
                ('object_id', models.PositiveIntegerField()),
                ('initial_errors', models.IntegerField(blank=True, null=True, verbose_name='Initialed Error Count')),
                ('skip_errors', models.IntegerField(blank=True, null=True, verbose_name='Skipped Error Count')),
                ('current_errors', models.IntegerField(blank=True, null=True, verbose_name='Current Error Count')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'ReviewLogs',
                'verbose_name': 'ReviewLog',
            },
            bases=('django_db_logger.statuslog',),
        ),
    ]
