# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20180615_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlog',
            name='current_errors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Error Count'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='initial_errors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Initialed Error Count'),
        ),
        migrations.AlterField(
            model_name='reviewlog',
            name='skip_errors',
            field=models.IntegerField(blank=True, null=True, verbose_name='Skipped Error Count'),
        ),
    ]
