# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-15 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20180615_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlog',
            name='skip_errors',
        ),
    ]
