# Generated by Django 2.2.14 on 2021-11-25 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0003_auto_20190507_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='managementtype',
            name='stratify_with',
            field=models.IntegerField(blank=True, choices=[(1, 'Field'), (2, 'Revenue')], null=True, verbose_name='Stratify With'),
        ),
        migrations.AddField(
            model_name='managementtype',
            name='type',
            field=models.IntegerField(blank=True, choices=[(1, 'Crop'), (2, 'Animal')], null=True, verbose_name='Product Type'),
        ),
        migrations.CreateModel(
            name='Stratify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hire', models.BooleanField(verbose_name='Is Hire')),
                ('min_field', models.FloatField(blank=True, null=True, verbose_name='Min Field')),
                ('max_field', models.FloatField(blank=True, null=True, verbose_name='Max Field')),
                ('min_revenue', models.PositiveIntegerField(blank=True, null=True, verbose_name='Min Revenue')),
                ('max_revenue', models.PositiveIntegerField(blank=True, null=True, verbose_name='Max Revenue')),
                ('code', models.PositiveIntegerField(db_index=True, verbose_name='Code')),
                ('population', models.PositiveIntegerField(verbose_name='Population(Statistic)')),
                ('management_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stratifies', to='surveys18.ManagementType', verbose_name='Management Type')),
            ],
            options={
                'verbose_name': 'Stratify',
                'verbose_name_plural': 'Stratify',
            },
        ),
        migrations.CreateModel(
            name='FarmerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.PositiveIntegerField(choices=[(1, 'North'), (2, 'Central'), (3, 'South'), (4, 'East')], verbose_name='Region')),
                ('create_time', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='Create Time')),
                ('update_time', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='Update Time')),
                ('stratify', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_stats', to='surveys18.Stratify', verbose_name='Stratify')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_stat', to='surveys18.Survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'Farmer Stat',
                'verbose_name_plural': 'Farmer Stat',
            },
        ),
    ]
