# Generated by Django 2.2.24 on 2024-04-05 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys24', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidy',
            name='heard_app',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='none_heard_app',
        ),
        migrations.AddField(
            model_name='survey',
            name='has_farm_outsource',
            field=models.BooleanField(default=False, verbose_name='Has Farm Outsource'),
        ),
        migrations.AddField(
            model_name='survey',
            name='non_has_farm_outsource',
            field=models.BooleanField(default=False, verbose_name='Non Has Farm Outsource'),
        ),
        migrations.CreateModel(
            name='ForeignLaborHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Number Of People')),
                ('avg_work_day', models.FloatField(blank=True, null=True, verbose_name='Average Work Day')),
                ('hire_type', models.PositiveIntegerField(choices=[(1, 'Long Term'), (2, 'Short Term')], verbose_name='Hire Type')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('month', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys24.Month', verbose_name='Month')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_labor_hires', to='surveys24.Survey', verbose_name='Survey')),
            ],
            options={
                'verbose_name': 'ForeignLaborHire',
                'verbose_name_plural': 'ForeignLaborHire',
                'ordering': ('month',),
            },
        ),
    ]
