# Generated by Django 2.2.24 on 2024-04-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys24', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='invalid_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Invalid Reason'),
        ),
        migrations.AddField(
            model_name='survey',
            name='is_invalid',
            field=models.BooleanField(default=False, verbose_name='Is Invalid'),
        ),
    ]
