# Generated by Django 2.2.10 on 2020-04-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys20", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="interviewee_relationship",
            field=models.CharField(
                blank=True,
                max_length=10,
                null=True,
                verbose_name="Interviewee Relationship",
            ),
        ),
    ]
