from django.urls import path

from .views import (
    SurveyListAPIView,
    SurveyUpdateAPIView,

    # Serializer Singleton
    ContentTypeSingletonListAPIView,
    SurveySingletonListAPIView,
    ShortTermHireSingletonListAPIView,
    LongTermHireSingletonListAPIView,
    NumberWorkersSingletonListAPIView,
    ShortTermLackSingletonListAPIView,
    LongTermLackSingletonListAPIView,
    NoSalaryHireSingletonListAPIView,
    SubsidySingletonListAPIView,
    RefuseSingletonListAPIView,
    PopulationSingletonListAPIView,
    PopulationAgeSingletonListAPIView,
    CropMarketingSingletonListAPIView,
    LivestockMarketingSingletonListAPIView,
    UnitSingletonListAPIView,
    ProductSingletonListAPIView,
    BusinessSingletonListAPIView,
    LandTypeSingletonListAPIView,
    LandAreaSingletonListAPIView,
    PhoneSingletonListAPIView,
    AddressMatchSingletonListAPIView,
    AnnualIncomeSingletonListAPIView,
    AgeScopeSingletonListAPIView,
    WorkTypeSingletonListAPIView,
    RefuseReasonSingletonListAPIView,
    FarmerWorkDaySingletonListAPIView,
    OtherFarmWorkSingletonListAPIView,
    RelationshipSingletonListAPIView,
    EducationLevelSingletonListAPIView,
    LifeStyleSingletonListAPIView,
    GenderSingletonListAPIView,
    LossSingletonListAPIView,
    FacilitySingletonListAPIView,
    ProductTypeSingletonListAPIView,
    ContractSingletonListAPIView,
    ManagementTypeSingletonListAPIView,
    FarmRelatedBusinessSingletonListAPIView,
    LandStatusSingletonListAPIView,
    LackSingletonListAPIView,
    IncomeRangeSingletonListAPIView,
    MarketTypeSingletonListAPIView,
    MonthSingletonListAPIView,
)

app_name = 'surveys18'

urlpatterns = [
    path('', SurveyListAPIView.as_view(), name='list'),
    path('update/', SurveyUpdateAPIView.as_view(), name='update'),

    # Serializer Singleton
    path('survey/', SurveySingletonListAPIView.as_view(), name='list_singleton_survey'),
    path('contenttype/', ContentTypeSingletonListAPIView.as_view(), name='list_singleton_contenttype'),
    path('shorttermhire/', ShortTermHireSingletonListAPIView.as_view(), name='list_singleton_shorttermhire'),
    path('longtermhire/', LongTermHireSingletonListAPIView.as_view(), name='list_singleton_longtermhire'),
    path('numberworkers/', NumberWorkersSingletonListAPIView.as_view(), name='list_singleton_numberworkers'),
    path('shorttermlack/', ShortTermLackSingletonListAPIView.as_view(), name='list_singleton_shorttermlack'),
    path('longtermlack/', LongTermLackSingletonListAPIView.as_view(), name='list_singleton_longtermlack'),
    path('nosalaryhire/', NoSalaryHireSingletonListAPIView.as_view(), name='list_singleton_nosalaryhire'),
    path('subsidy/', SubsidySingletonListAPIView.as_view(), name='list_singleton_subsidy'),
    path('refuse/', RefuseSingletonListAPIView.as_view(), name='list_singleton_refuse'),
    path('population/', PopulationSingletonListAPIView.as_view(), name='list_singleton_population'),
    path('populationage/', PopulationAgeSingletonListAPIView.as_view(), name='list_singleton_populationage'),
    path('cropmarketing/', CropMarketingSingletonListAPIView.as_view(), name='list_singleton_cropmarketing'),
    path('livestockmarketing/', LivestockMarketingSingletonListAPIView.as_view(), name='list_singleton_livestockmarketing'),
    path('unit/', UnitSingletonListAPIView.as_view(), name='list_singleton_unit'),
    path('product/', ProductSingletonListAPIView.as_view(), name='list_singleton_product'),
    path('business/', BusinessSingletonListAPIView.as_view(), name='list_singleton_business'),
    path('landtype/', LandTypeSingletonListAPIView.as_view(), name='list_singleton_landtype'),
    path('landarea/', LandAreaSingletonListAPIView.as_view(), name='list_singleton_landarea'),
    path('phone/', PhoneSingletonListAPIView.as_view(), name='list_singleton_phone'),
    path('addressmatch/', AddressMatchSingletonListAPIView.as_view(), name='list_singleton_addressmatch'),
    path('annualincome/', AnnualIncomeSingletonListAPIView.as_view(), name='list_singleton_annualincome'),

    # Serializer Singleton No Pagination
    path('agescope/', AgeScopeSingletonListAPIView.as_view(), name='list_singleton_agescope'),
    path('worktype/', WorkTypeSingletonListAPIView.as_view(), name='list_singleton_worktype'),
    path('refusereason/', RefuseReasonSingletonListAPIView.as_view(), name='list_singleton_refusereason'),
    path('farmerworkday/', FarmerWorkDaySingletonListAPIView.as_view(), name='list_singleton_farmerworkday'),
    path('otherfarmwork/', OtherFarmWorkSingletonListAPIView.as_view(), name='list_singleton_otherfarmwork'),
    path('relationship/', RelationshipSingletonListAPIView.as_view(), name='list_singleton_relationship'),
    path('educationlevel/', EducationLevelSingletonListAPIView.as_view(), name='list_singleton_educationlevel'),
    path('lifestyle/', LifeStyleSingletonListAPIView.as_view(), name='list_singleton_lifestyle'),
    path('gender/', GenderSingletonListAPIView.as_view(), name='list_singleton_gender'),
    path('loss/', LossSingletonListAPIView.as_view(), name='list_singleton_loss'),
    path('facility/', FacilitySingletonListAPIView.as_view(), name='list_singleton_facility'),
    path('producttype/', ProductTypeSingletonListAPIView.as_view(), name='list_singleton_producttype'),
    path('contract/', ContractSingletonListAPIView.as_view(), name='list_singleton_contract'),
    path('managementtype/', ManagementTypeSingletonListAPIView.as_view(), name='list_singleton_managementtype'),
    path('farmrelatedbusiness/', FarmRelatedBusinessSingletonListAPIView.as_view(), name='list_singleton_farmrelatedbusiness'),
    path('landstatus/', LandStatusSingletonListAPIView.as_view(), name='list_singleton_landstatus'),
    path('lack/', LackSingletonListAPIView.as_view(), name='list_singleton_lack'),
    path('incomerange/', IncomeRangeSingletonListAPIView.as_view(), name='list_singleton_incomerange'),
    path('markettype/', MarketTypeSingletonListAPIView.as_view(), name='list_singleton_markettype'),
    path('month/', MonthSingletonListAPIView.as_view(), name='list_singleton_month'),
]
