# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivestockMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raising_number', models.IntegerField(blank=True, null=True, verbose_name='Raising Number')),
                ('total_yield', models.IntegerField(blank=True, null=True, verbose_name='Total Yield')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='Unit Price')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Livestock Marketing',
                'verbose_name_plural': 'Livestock Marketing',
            },
        ),
        migrations.RemoveField(
            model_name='animalmarketing',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='animalmarketing',
            name='loss',
        ),
        migrations.RemoveField(
            model_name='animalmarketing',
            name='product',
        ),
        migrations.RemoveField(
            model_name='animalmarketing',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='animalmarketing',
            name='unit',
        ),
        migrations.AlterModelOptions(
            name='contract',
            options={'verbose_name': 'LivestockUnit', 'verbose_name_plural': 'LivestockUnit'},
        ),
        migrations.DeleteModel(
            name='AnimalMarketing',
        ),
        migrations.AddField(
            model_name='livestockmarketing',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='surveys.Contract', verbose_name='Contract'),
        ),
        migrations.AddField(
            model_name='livestockmarketing',
            name='loss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livestock_marketing_loss', to='surveys.Loss', verbose_name='Loss'),
        ),
        migrations.AddField(
            model_name='livestockmarketing',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livestock_marketing_product', to='surveys.Product', verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='livestockmarketing',
            name='survey',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='livestock_marketings', to='surveys.Survey', verbose_name='Survey'),
        ),
        migrations.AddField(
            model_name='livestockmarketing',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='livestock_marketing_unit', to='surveys.Unit', verbose_name='Unit'),
        ),
    ]
