# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-16 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_auto_20180516_0813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='longtermlack',
            old_name='number_of_people',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='nosalaryhire',
            old_name='number_of_people',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='shorttermlack',
            old_name='number_of_people',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='subsidy',
            old_name='number_of_people',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='application_time',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='day_delta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Day Delta'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='hour_delta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hour Delta'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='month_delta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Month Delta'),
        ),
    ]
