# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0006_farmrelatedbusiness_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropmarketing',
            name='has_facility',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Has Facility'),
        ),
        migrations.AlterField(
            model_name='farmrelatedbusiness',
            name='has_business',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Has Business'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='is_subsidy',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Is Subsidy'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_hire',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Yes')], null=True, verbose_name='Hire'),
        ),
    ]
