# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0007_auto_20180517_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livestockmarketing',
            options={'verbose_name': 'LivestockMarketing', 'verbose_name_plural': 'LivestockMarketing'},
        ),
        migrations.AlterModelOptions(
            name='longtermhire',
            options={'verbose_name': 'LongTermHire', 'verbose_name_plural': 'LongTermHire'},
        ),
        migrations.AlterModelOptions(
            name='populationage',
            options={'verbose_name': 'PopulationAge', 'verbose_name_plural': 'PopulationAge'},
        ),
        migrations.AlterModelOptions(
            name='refusereason',
            options={'verbose_name': 'RefuseReason', 'verbose_name_plural': 'RefuseReason'},
        ),
        migrations.AlterModelOptions(
            name='worktype',
            options={'verbose_name': 'WorkType', 'verbose_name_plural': 'WorkType'},
        ),
    ]
