# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-17 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0008_auto_20180517_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerworkday',
            name='code',
            field=models.IntegerField(default=1, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
