# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-21 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0012_auto_20180517_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='is_updated',
            field=models.BooleanField(default=False, verbose_name='Is Updated'),
        ),
    ]
