# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Area Value')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name_plural': 'LandArea',
                'verbose_name': 'LandArea',
            },
        ),
        migrations.CreateModel(
            name='LandStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name_plural': 'LandStatus',
                'verbose_name': 'LandStatus',
            },
        ),
        migrations.CreateModel(
            name='LandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name_plural': 'LandType',
                'verbose_name': 'LandType',
            },
        ),
        migrations.RemoveField(
            model_name='farmerlandarea',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='farmerlandarea',
            name='type',
        ),
        migrations.DeleteModel(
            name='FarmerLandArea',
        ),
        migrations.DeleteModel(
            name='FarmerLandType',
        ),
        migrations.AddField(
            model_name='landarea',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_areas', to='surveys18.LandStatus', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='landarea',
            name='survey',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_areas', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AddField(
            model_name='landarea',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_areas', to='surveys18.LandType', verbose_name='Type'),
        ),
    ]
