# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-13 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0002_auto_20180611_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualincome',
            name='income_range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys18.IncomeRange', verbose_name='Income Range'),
        ),
        migrations.AlterField(
            model_name='annualincome',
            name='market_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys18.MarketType', verbose_name='Market Type'),
        ),
        migrations.AlterField(
            model_name='annualincome',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_incomes', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='business',
            name='farm_related_business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business', to='surveys18.FarmRelatedBusiness', verbose_name='Farm Related Business'),
        ),
        migrations.AlterField(
            model_name='cropmarketing',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_marketings', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='landarea',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_areas', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='livestockmarketing',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock_marketings', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='longtermhire',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_hires', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='longtermlack',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='long_term_lacks', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='nosalaryhire',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='no_salary_hires', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='population',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='populations', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='populationage',
            name='age_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys18.AgeScope', verbose_name='Age Scope'),
        ),
        migrations.AlterField(
            model_name='populationage',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys18.Gender', verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='refuse',
            name='reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refuse', to='surveys18.RefuseReason', verbose_name='Refuse'),
        ),
        migrations.AlterField(
            model_name='refuse',
            name='subsidy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refuses', to='surveys18.Subsidy', verbose_name='Subsidy'),
        ),
        migrations.AlterField(
            model_name='shorttermhire',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_term_hires', to='surveys18.Survey', verbose_name='Survey'),
        ),
        migrations.AlterField(
            model_name='shorttermlack',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_term_lacks', to='surveys18.Survey', verbose_name='Survey'),
        ),
    ]
