# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0002_auto_20180523_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtype',
            name='statuses',
            field=models.ManyToManyField(related_name='land_type', to='surveys18.LandStatus', verbose_name='Land Statuses'),
        ),
    ]
