# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-19 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0003_auto_20180613_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='builderfile',
            name='token',
            field=models.TextField(blank=True, null=True, verbose_name='Token String'),
        ),
        migrations.AlterField(
            model_name='builderfile',
            name='datafile',
            field=models.FileField(blank=True, null=True, upload_to='surveys18/builders/', verbose_name='DataFile'),
        ),
    ]
