# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-23 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0003_landtype_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populationage',
            name='is_under_15',
        ),
        migrations.AddField(
            model_name='agescope',
            name='group',
            field=models.IntegerField(default=0, verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='populationage',
            name='age_scope',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='surveys18.AgeScope', verbose_name='Age Scope'),
            preserve_default=False,
        ),
    ]
