# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-19 06:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0005_auto_20180619_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='builderfile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
