# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 06:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0006_auto_20180619_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='landtype',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_type', to='surveys18.Unit', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='builderfile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys18.BuilderFileType', verbose_name='BuilderFileType'),
        ),
    ]
