# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0006_auto_20180524_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermhire',
            name='month',
        ),
        migrations.AddField(
            model_name='longtermhire',
            name='months',
            field=models.ManyToManyField(related_name='long_term_hires', to='surveys18.Month', verbose_name='Months'),
        ),
    ]
