# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-24 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0007_auto_20180524_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='address',
        ),
    ]
