# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0007_auto_20180620_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropmarketing',
            options={'ordering': ('land_number', 'id'), 'verbose_name': 'CropMarketing', 'verbose_name_plural': 'CropMarketing'},
        ),
        migrations.AlterModelOptions(
            name='livestockmarketing',
            options={'ordering': ('id',), 'verbose_name': 'LivestockMarketing', 'verbose_name_plural': 'LivestockMarketing'},
        ),
        migrations.AlterModelOptions(
            name='longtermhire',
            options={'ordering': ('id',), 'verbose_name': 'LongTermHire', 'verbose_name_plural': 'LongTermHire'},
        ),
        migrations.AlterModelOptions(
            name='population',
            options={'ordering': ('id', 'relationship'), 'verbose_name': 'Population', 'verbose_name_plural': 'Population'},
        ),
        migrations.AddField(
            model_name='landtype',
            name='has_land',
            field=models.BooleanField(default=True, verbose_name='Has Land'),
        ),
    ]
