# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-28 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0008_remove_survey_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='read_only',
            new_name='readonly',
        ),
    ]
