# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-20 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0008_auto_20180620_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropmarketing',
            options={'ordering': ('id', 'land_number'), 'verbose_name': 'CropMarketing', 'verbose_name_plural': 'CropMarketing'},
        ),
    ]
