# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-22 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0009_auto_20180620_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='management_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='surveys', to='surveys18.ManagementType', verbose_name='Management Types'),
        ),
    ]
