# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-28 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0009_auto_20180528_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmatch',
            name='different',
        ),
    ]
