# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-28 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0010_remove_addressmatch_different'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='farm_related_businesses',
        ),
        migrations.RemoveField(
            model_name='business',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='management',
            name='survey',
        ),
        migrations.RemoveField(
            model_name='management',
            name='types',
        ),
        migrations.AddField(
            model_name='survey',
            name='farm_related_businesses',
            field=models.ManyToManyField(related_name='survey', to='surveys18.FarmRelatedBusiness', verbose_name='Farm Related Business'),
        ),
        migrations.AddField(
            model_name='survey',
            name='management_types',
            field=models.ManyToManyField(related_name='survey', to='surveys18.ManagementType', verbose_name='Management Types'),
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Management',
        ),
    ]
