# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0011_auto_20180528_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmatch',
            name='different',
            field=models.BooleanField(default=False, verbose_name='Address Different'),
        ),
    ]
