# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0012_addressmatch_different'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmatch',
            name='different',
        ),
        migrations.AddField(
            model_name='addressmatch',
            name='mismatch',
            field=models.BooleanField(default=False, verbose_name='Address MisMatch'),
        ),
    ]
