# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-29 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0016_auto_20180529_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='surveys18.Survey', verbose_name='Survey'),
        ),
    ]
