# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-30 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0020_auto_20180529_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(blank=True, max_length=100, null=True, verbose_name='Extra')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Refuse',
                'verbose_name_plural': 'Refuse',
            },
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='reasons',
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='remark',
        ),
        migrations.AddField(
            model_name='refusereason',
            name='has_extra',
            field=models.BooleanField(default=False, verbose_name='Has Extra'),
        ),
        migrations.AddField(
            model_name='refuse',
            name='reason',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refuse', to='surveys18.RefuseReason', verbose_name='Refuse'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='refuses',
            field=models.ManyToManyField(blank=True, related_name='subsidy', to='surveys18.Refuse', verbose_name='subsidies'),
        ),
    ]
