# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0023_auto_20180530_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidy',
            name='is_subsidy',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='no',
            field=models.BooleanField(default=False, verbose_name='Non Subsidy'),
        ),
        migrations.AddField(
            model_name='subsidy',
            name='yes',
            field=models.BooleanField(default=False, verbose_name='Has Subsidy'),
        ),
    ]
