# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-31 03:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0025_auto_20180531_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subsidy',
            old_name='is_subsidy',
            new_name='has_subsidy',
        ),
    ]
