# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0027_auto_20180531_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsidy',
            name='none_subsidy',
            field=models.BooleanField(default=False, verbose_name='None Subsidy'),
        ),
        migrations.AlterField(
            model_name='subsidy',
            name='has_subsidy',
            field=models.BooleanField(default=False, verbose_name='Has Subsidy'),
        ),
    ]
