# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-05 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0028_auto_20180605_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='management_types',
            field=models.ManyToManyField(related_name='surveys', to='surveys18.ManagementType', verbose_name='Management Types'),
        ),
    ]
