# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 01:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0029_auto_20180605_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermhire',
            name='avg_work_day',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Work Day'),
        ),
        migrations.AlterField(
            model_name='shorttermhire',
            name='avg_work_day',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Work Day'),
        ),
    ]
