# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0030_auto_20180607_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermhire',
            name='months',
            field=models.ManyToManyField(blank=True, related_name='long_term_hires', to='surveys18.Month', verbose_name='Months'),
        ),
    ]
