# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0031_auto_20180607_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorttermlack',
            name='work_types',
        ),
        migrations.AddField(
            model_name='shorttermlack',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='short_term_lacks', to='surveys18.WorkType', verbose_name='Work Type'),
        ),
        migrations.AlterField(
            model_name='longtermlack',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_term_lacks', to='surveys18.WorkType', verbose_name='Work Type'),
        ),
    ]
