# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0032_auto_20180607_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='longtermhire',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='long_term_hires', to='surveys18.WorkType', verbose_name='Work Type'),
        ),
    ]
