# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-07 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0033_auto_20180607_1503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nosalaryhire',
            options={'ordering': ('month',), 'verbose_name': 'NoSalaryHire', 'verbose_name_plural': 'NoSalaryHire'},
        ),
        migrations.AlterModelOptions(
            name='shorttermhire',
            options={'ordering': ('month',), 'verbose_name': 'ShortTermHire', 'verbose_name_plural': 'ShortTermHire'},
        ),
        migrations.RemoveField(
            model_name='subsidy',
            name='refuses',
        ),
        migrations.AddField(
            model_name='refuse',
            name='subsidy',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='refuses', to='surveys18.Subsidy', verbose_name='Subsidy'),
            preserve_default=False,
        ),
    ]
