# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-08 07:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0036_auto_20180608_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='builderfile',
            options={'verbose_name': 'BuilderFile', 'verbose_name_plural': 'BuilderFile'},
        ),
        migrations.AlterField(
            model_name='builderfile',
            name='datafile',
            field=models.FileField(default=datetime.datetime(2018, 6, 8, 7, 29, 43, 6881, tzinfo=utc), upload_to='', verbose_name='DataFile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='builderfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
