# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-09 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('surveys18', '0038_auto_20180609_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderFileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'BuilderFileType',
                'verbose_name_plural': 'BuilderFileType',
            },
        ),
        migrations.AlterModelOptions(
            name='month',
            options={'verbose_name': 'Month', 'verbose_name_plural': 'Month'},
        ),
        migrations.AddField(
            model_name='month',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='builderfile',
            name='datafile',
            field=models.FileField(upload_to='surveys18/builders/', verbose_name='DataFile'),
        ),
        migrations.AddField(
            model_name='builderfile',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys18.BuilderFileType', verbose_name='Investigator'),
        ),
    ]
