from django.contrib import admin

from .models import (
    Survey19,
    Phone,
    AddressMatch,
    FarmLocation,
    LandStatus,
    LandType,
    LandArea,
    Business,
    FarmRelatedBusiness,
    ManagementType,
    CropMarketing,
    LivestockMarketing,
    ProductType,
    ProductCode,
    Product,
    Unit,
    Loss,
    Contract,
    AnnualIncome,
    MarketType,
    IncomeRange,
    AgeScope,
    PopulationAge,
    Population,
    Relationship,
    Gender,
    EducationLevel,
    FarmerWorkDay,
    LifeStyle,
    LongTermHire,
    ShortTermHire,
    NoSalaryHire,
    NumberWorkers,
    Lack,
    LongTermLack,
    ShortTermLack,
    WorkType,
    Subsidy,
    Refuse,
    RefuseReason,
    Month,
)


admin.site.register(Survey19)
admin.site.register(Phone)
admin.site.register(AddressMatch)
admin.site.register(FarmLocation)
admin.site.register(LandStatus)
admin.site.register(LandType)
admin.site.register(LandArea)
admin.site.register(Business)
admin.site.register(FarmRelatedBusiness)
admin.site.register(ManagementType)
admin.site.register(CropMarketing)
admin.site.register(LivestockMarketing)
admin.site.register(ProductType)
admin.site.register(ProductCode)
admin.site.register(Product)
admin.site.register(Unit)
admin.site.register(Loss)
admin.site.register(Contract)
admin.site.register(AnnualIncome)
admin.site.register(MarketType)
admin.site.register(IncomeRange)
admin.site.register(AgeScope)
admin.site.register(PopulationAge)
admin.site.register(Population)
admin.site.register(Relationship)
admin.site.register(Gender)
admin.site.register(EducationLevel)
admin.site.register(FarmerWorkDay)
admin.site.register(LifeStyle)
admin.site.register(LongTermHire)
admin.site.register(ShortTermHire)
admin.site.register(NoSalaryHire)
admin.site.register(NumberWorkers)
admin.site.register(Lack)
admin.site.register(LongTermLack)
admin.site.register(ShortTermLack)
admin.site.register(WorkType)
admin.site.register(Subsidy)
admin.site.register(Refuse)
admin.site.register(RefuseReason)
admin.site.register(Month)
