# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-07 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.BooleanField(default=False, verbose_name='Address Match')),
                ('different', models.BooleanField(default=False, verbose_name='Address Different')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'AddressMatch',
                'verbose_name_plural': 'AddressMatch',
            },
        ),
        migrations.CreateModel(
            name='AnnualIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'AnnualIncome',
                'verbose_name_plural': 'AnnualIncomes',
            },
        ),
        migrations.CreateModel(
            name='BaseFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=12, verbose_name='Farmer Id')),
                ('farmer_name', models.CharField(max_length=10, verbose_name='Farmer Name')),
                ('total_pages', models.IntegerField(verbose_name='Total Pages')),
                ('page', models.IntegerField(verbose_name='Page')),
                ('ori_class', models.IntegerField(blank=True, null=True, verbose_name='Original Class')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('investigator_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Investigator Name')),
                ('investigationp_period', models.IntegerField(blank=True, null=True, verbose_name='Investigation Period')),
                ('investigation_date', models.DateField(blank=True, null=True, verbose_name='Investigation Date')),
                ('investigation_distance_km', models.IntegerField(blank=True, null=True, verbose_name='Investigation Distance KM')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('read_only', models.BooleanField(default=True, verbose_name='Read Only')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'BaseFarmer',
                'verbose_name_plural': 'BaseFarmer',
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basefarmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Business',
            },
        ),
        migrations.CreateModel(
            name='FarmerLandArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True, verbose_name='Area Value')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_land_areas', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
            ],
            options={
                'verbose_name': 'FarmerLandArea',
                'verbose_name_plural': 'FarmerLandArea',
            },
        ),
        migrations.CreateModel(
            name='FarmerLandType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Land Type Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'FarmerLandType',
                'verbose_name_plural': 'FarmerLandType',
            },
        ),
        migrations.CreateModel(
            name='FarmerProductionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Production Type Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'FarmerProductionType',
                'verbose_name_plural': 'FarmerProductionType',
            },
        ),
        migrations.CreateModel(
            name='FarmRelatedBusiness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Related Business Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'FarmRelatedBusiness',
                'verbose_name_plural': 'FarmRelatedBusiness',
            },
        ),
        migrations.CreateModel(
            name='IncomeRangeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('minimum', models.IntegerField(verbose_name='Minimum Income')),
                ('maximum', models.IntegerField(verbose_name='Maximum Income')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'IncomeRangeCode',
                'verbose_name_plural': 'IncomeRangeCodes',
            },
        ),
        migrations.CreateModel(
            name='Lack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Lack',
                'verbose_name_plural': 'Lack',
            },
        ),
        migrations.CreateModel(
            name='MarketType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'MarketType',
                'verbose_name_plural': 'MarketTypes',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phone',
            },
        ),
        migrations.AddField(
            model_name='farmerlandarea',
            name='farmer_land_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_land_type', to='basefarmers.FarmerLandType', verbose_name='Farmer Land Type'),
        ),
        migrations.AddField(
            model_name='farmerlandarea',
            name='farmer_production_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_production_type', to='basefarmers.FarmerProductionType', verbose_name='Farmer Production Type'),
        ),
        migrations.AddField(
            model_name='business',
            name='farm_related_business',
            field=models.ManyToManyField(related_name='business', to='basefarmers.FarmRelatedBusiness', verbose_name='Farm Related Business'),
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='lack',
            field=models.ManyToManyField(blank=True, to='basefarmers.Lack', verbose_name='Lack'),
        ),
        migrations.AddField(
            model_name='annualincome',
            name='basefarmer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_incomes', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
        migrations.AddField(
            model_name='annualincome',
            name='income_range_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basefarmers.IncomeRangeCode', verbose_name='Income Range Code'),
        ),
        migrations.AddField(
            model_name='annualincome',
            name='market_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basefarmers.MarketType', verbose_name='Market Type'),
        ),
        migrations.AddField(
            model_name='addressmatch',
            name='basefarmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_match', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
    ]
