# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseFarmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_id', models.CharField(max_length=12, verbose_name='Farmer Id')),
                ('farmer_name', models.CharField(max_length=10, verbose_name='Farmer Name')),
                ('total_pages', models.IntegerField(verbose_name='Total Pages')),
                ('page', models.IntegerField(verbose_name='Page')),
                ('is_address_match', models.CharField(blank=True, max_length=1, null=True, verbose_name='Is Address Match')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('ori_class', models.IntegerField(blank=True, null=True, verbose_name='Original Class')),
                ('is_lack', models.CharField(blank=True, max_length=1, null=True, verbose_name='Is Lack')),
                ('investigator_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Investigator Name')),
                ('investigation_time', models.IntegerField(blank=True, null=True, verbose_name='Investigation Time')),
                ('investigation_date', models.DateField(blank=True, null=True, verbose_name='Investigation Date')),
                ('investigation_distance_km', models.IntegerField(blank=True, null=True, verbose_name='Investigation Distance KM')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('annual_income', models.ManyToManyField(to='basefarmers.AnnualIncome', verbose_name='Annual Income')),
            ],
            options={
                'verbose_name': 'AnnualIncome',
                'verbose_name_plural': 'AnnualIncomes',
            },
        ),
    ]
