# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-07 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Management',
                'verbose_name_plural': 'Management',
            },
        ),
        migrations.CreateModel(
            name='ManagementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Management Type Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'ManagementType',
                'verbose_name_plural': 'ManagementType',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AddField(
            model_name='farmrelatedbusiness',
            name='has_business',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Has Business'),
        ),
        migrations.AlterField(
            model_name='basefarmer',
            name='farmer_name',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Farmer Name'),
        ),
        migrations.AddField(
            model_name='management',
            name='basefarmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='management', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
        migrations.AddField(
            model_name='management',
            name='management_type',
            field=models.ManyToManyField(related_name='management', to='basefarmers.FarmRelatedBusiness', verbose_name='Management Type'),
        ),
    ]
