# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0002_auto_20180507_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='farm_related_business',
            field=models.ManyToManyField(related_name='farm_related_business', to='basefarmers.FarmRelatedBusiness', verbose_name='Farm Related Business'),
        ),
        migrations.AlterField(
            model_name='management',
            name='management_type',
            field=models.ManyToManyField(related_name='management_type', to='basefarmers.FarmRelatedBusiness', verbose_name='Management Type'),
        ),
    ]
