# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-03 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0002_basefarmer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefarmer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='basefarmer',
            name='is_address_match',
        ),
        migrations.RemoveField(
            model_name='basefarmer',
            name='is_lack',
        ),
    ]
