# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0003_auto_20180503_1845'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basefarmer',
            options={'verbose_name': 'BaseFarmer', 'verbose_name_plural': 'BaseFarmer'},
        ),
    ]
