# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0003_auto_20180508_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Contract Code')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Contract Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'AnimalUnit',
                'verbose_name_plural': 'AnimalUnit',
            },
        ),
        migrations.CreateModel(
            name='Loss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Loss Code')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Loss Name')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Loss Type')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Loss',
                'verbose_name_plural': 'Loss',
            },
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Product Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Code Name')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Product Type')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'ProductCode',
                'verbose_name_plural': 'ProductCode',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Unit Code')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unit Name')),
                ('type', models.CharField(blank=True, max_length=20, null=True, verbose_name='Unit Type')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Unit',
            },
        ),
    ]
