# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0004_contract_loss_productcode_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_number', models.IntegerField(blank=True, null=True, verbose_name='Land Number')),
                ('land_area', models.IntegerField(blank=True, null=True, verbose_name='Land Area')),
                ('plant_times', models.IntegerField(blank=True, null=True, verbose_name='Plant Times')),
                ('total_yield', models.IntegerField(blank=True, null=True, verbose_name='Total Yield')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='Unit Price')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_marketing', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
                ('loss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loss', to='basefarmers.Loss', verbose_name='Loss')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_code', to='basefarmers.ProductCode', verbose_name='Product Code')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='basefarmers.Unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'CropMarketing',
                'verbose_name_plural': 'CropMarketing',
            },
        ),
    ]
