# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0004_auto_20180504_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefarmer',
            name='annual_income',
            field=models.ManyToManyField(blank=True, null=True, to='basefarmers.AnnualIncome', verbose_name='Annual Income'),
        ),
    ]
