# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0005_cropmarketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalMarketing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raising_number', models.IntegerField(blank=True, null=True, verbose_name='Raising Number')),
                ('total_yield', models.IntegerField(blank=True, null=True, verbose_name='Total Yield')),
                ('unit_price', models.IntegerField(blank=True, null=True, verbose_name='Unit Price')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_marketing', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='basefarmers.Contract', verbose_name='Contract')),
                ('loss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_marketing_loss', to='basefarmers.Loss', verbose_name='Loss')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_marketing_product_code', to='basefarmers.ProductCode', verbose_name='Product Code')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='animal_marketing_unit', to='basefarmers.Unit', verbose_name='Unit')),
            ],
            options={
                'verbose_name': 'AnimalMarketing',
                'verbose_name_plural': 'AnimalMarketing',
            },
        ),
        migrations.CreateModel(
            name='IsFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Facility Code')),
                ('name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Facility Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'IsFacility',
                'verbose_name_plural': 'IsFacility',
            },
        ),
        migrations.AlterField(
            model_name='cropmarketing',
            name='loss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_marketing_loss', to='basefarmers.Loss', verbose_name='Loss'),
        ),
        migrations.AlterField(
            model_name='cropmarketing',
            name='product_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_marketing_product_code', to='basefarmers.ProductCode', verbose_name='Product Code'),
        ),
        migrations.AlterField(
            model_name='cropmarketing',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crop_marketing_unit', to='basefarmers.Unit', verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='cropmarketing',
            name='is_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_facility', to='basefarmers.IsFacility', verbose_name='Is Facility'),
        ),
    ]
