# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0006_auto_20180504_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefarmer',
            name='read_only',
        ),
    ]
