# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-08 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0006_auto_20180508_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_times', models.IntegerField(blank=True, null=True, verbose_name='Plant Times')),
                ('under_15_men', models.IntegerField(blank=True, null=True, verbose_name='Under 15 Men')),
                ('under_15_women', models.IntegerField(blank=True, null=True, verbose_name='Under 15 Women')),
                ('over_15_men', models.IntegerField(blank=True, null=True, verbose_name='Over 15 Men')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_number', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
            ],
            options={
                'verbose_name': 'PopulationNumber',
                'verbose_name_plural': 'PopulationNumber',
            },
        ),
    ]
