# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0007_remove_basefarmer_read_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefarmer',
            name='read_only',
            field=models.BooleanField(default=True, verbose_name='Read Only'),
        ),
    ]
