# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0007_populationnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='populationnumber',
            name='plant_times',
        ),
        migrations.AddField(
            model_name='populationnumber',
            name='over_15_women',
            field=models.IntegerField(blank=True, null=True, verbose_name='Over 15 Women'),
        ),
        migrations.AlterField(
            model_name='populationnumber',
            name='basefarmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='population_number', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
    ]
