# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0008_auto_20180509_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevelCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Education Level Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'EducationLevelCode',
                'verbose_name_plural': 'EducationLevelCode',
            },
        ),
        migrations.CreateModel(
            name='FarmerWorkDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Farmer Work Day Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'FarmerWorkDay',
                'verbose_name_plural': 'FarmerWorkDay',
            },
        ),
        migrations.CreateModel(
            name='LifeStyleCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Education Level Name')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'LifeStyleCode',
                'verbose_name_plural': 'LifeStyleCode',
            },
        ),
        migrations.CreateModel(
            name='OtherFarmWorkCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Other Farm Work Code Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'OtherFarmWorkCode',
                'verbose_name_plural': 'OtherFarmWorkCode',
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(blank=True, max_length=5, null=True, verbose_name='Sex')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Birth Year')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='population', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
                ('education_level_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education_level_code', to='basefarmers.EducationLevelCode', verbose_name='Education Level Code')),
                ('farmer_work_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_work_day', to='basefarmers.FarmerWorkDay', verbose_name='Farmer Work Day')),
                ('life_style_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='life_style_code', to='basefarmers.LifeStyleCode', verbose_name='Life Style Code')),
                ('other_farm_work_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='other_farm_work_code', to='basefarmers.OtherFarmWorkCode', verbose_name='Other Farm Work Code')),
            ],
            options={
                'verbose_name': 'Population',
                'verbose_name_plural': 'Population',
            },
        ),
        migrations.CreateModel(
            name='RelationshipCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Relationship Code Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'RelationshipCode',
                'verbose_name_plural': 'RelationshipCode',
            },
        ),
        migrations.AddField(
            model_name='population',
            name='relationship_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_code', to='basefarmers.RelationshipCode', verbose_name='Relationship Code'),
        ),
    ]
