# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0008_basefarmer_read_only'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsAddressMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.BooleanField(default=False, verbose_name='Address Match')),
                ('different', models.BooleanField(default=False, verbose_name='Address Different')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'IsAddressMatch',
                'verbose_name_plural': 'IsAddressMatch',
            },
        ),
        migrations.RemoveField(
            model_name='basefarmer',
            name='investigation_time',
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='investigationp_period',
            field=models.IntegerField(blank=True, null=True, verbose_name='Investigation Period'),
        ),
        migrations.AlterField(
            model_name='basefarmer',
            name='page',
            field=models.IntegerField(verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='basefarmer',
            name='total_pages',
            field=models.IntegerField(verbose_name='Total Pages'),
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='is_address_match',
            field=models.ManyToManyField(blank=True, null=True, to='basefarmers.IsAddressMatch', verbose_name='Is Address Match'),
        ),
    ]
