# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 09:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0009_auto_20180510_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifestylecode',
            name='age',
        ),
    ]
