# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 08:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0009_auto_20180504_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefarmer',
            name='is_address_match',
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='is_address_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basefarmers.IsAddressMatch', verbose_name='Is Address Match'),
        ),
    ]
