# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0010_auto_20180504_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enough_worker', models.BooleanField(default=False, verbose_name='Enough Worker')),
                ('uncertain_worker', models.BooleanField(default=False, verbose_name='Uncertain Worker')),
                ('add_value_others', models.BooleanField(default=False, verbose_name='Add Value Others')),
                ('is_lack', models.BooleanField(default=False, verbose_name='Is Lack')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'IsLack',
                'verbose_name_plural': 'IsLack',
            },
        ),
        migrations.RenameModel(
            old_name='IsAddressMatch',
            new_name='AddressMatch',
        ),
        migrations.RemoveField(
            model_name='basefarmer',
            name='is_address_match',
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='address_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basefarmer', to='basefarmers.AddressMatch', verbose_name='Is Address Match'),
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='lack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basefarmer', to='basefarmers.Lack', verbose_name='Is Address Match'),
        ),
    ]
