# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0010_remove_lifestylecode_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifestylecode',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Life Style Code Name'),
        ),
    ]
