# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0011_auto_20180504_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addressmatch',
            options={'verbose_name': 'AddressMatch', 'verbose_name_plural': 'AddressMatch'},
        ),
        migrations.AlterModelOptions(
            name='lack',
            options={'verbose_name': 'Lack', 'verbose_name_plural': 'Lack'},
        ),
        migrations.RemoveField(
            model_name='basefarmer',
            name='address_match',
        ),
        migrations.RemoveField(
            model_name='lack',
            name='add_value_others',
        ),
        migrations.RemoveField(
            model_name='lack',
            name='enough_worker',
        ),
        migrations.RemoveField(
            model_name='lack',
            name='is_lack',
        ),
        migrations.RemoveField(
            model_name='lack',
            name='uncertain_worker',
        ),
        migrations.AddField(
            model_name='addressmatch',
            name='basefarmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basefarmer', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='lack',
            name='name',
            field=models.BooleanField(default=False, verbose_name='Is Lack Name'),
        ),
        migrations.AlterField(
            model_name='basefarmer',
            name='lack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basefarmers.Lack', verbose_name='Lack'),
        ),
    ]
