# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0012_applicationcontent_subsidy'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Age Scope Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'AgeScope',
                'verbose_name_plural': 'AgeScope',
            },
        ),
        migrations.CreateModel(
            name='LongTermForHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_unit_day', models.IntegerField(blank=True, null=True, verbose_name='Work Unit Day')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_hire', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
            ],
            options={
                'verbose_name': 'LongTermForHire',
                'verbose_name_plural': 'LongTermForHire',
            },
        ),
        migrations.CreateModel(
            name='WorkTypeCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True, verbose_name='Work Type Code')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='WorkType Code Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'WorkTypeCode',
                'verbose_name_plural': 'WorkTypeCode',
            },
        ),
        migrations.AddField(
            model_name='longtermforhire',
            name='work_type_code',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_type_code_longterm_hire', to='basefarmers.WorkTypeCode', verbose_name='Work Type Code'),
        ),
    ]
