# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0012_auto_20180504_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lack',
            name='name',
        ),
        migrations.AddField(
            model_name='lack',
            name='add_value_others',
            field=models.BooleanField(default=False, verbose_name='Add Value Others'),
        ),
        migrations.AddField(
            model_name='lack',
            name='enough_worker',
            field=models.BooleanField(default=False, verbose_name='Enough Worker'),
        ),
        migrations.AddField(
            model_name='lack',
            name='is_lack',
            field=models.BooleanField(default=False, verbose_name='Is Lack'),
        ),
        migrations.AddField(
            model_name='lack',
            name='uncertain_worker',
            field=models.BooleanField(default=False, verbose_name='Uncertain Worker'),
        ),
    ]
