# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0013_auto_20180504_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lack',
            name='add_value_others',
        ),
        migrations.RemoveField(
            model_name='lack',
            name='enough_worker',
        ),
        migrations.RemoveField(
            model_name='lack',
            name='is_lack',
        ),
        migrations.RemoveField(
            model_name='lack',
            name='uncertain_worker',
        ),
        migrations.AddField(
            model_name='lack',
            name='name',
            field=models.BooleanField(default=False, verbose_name='Is Lack Name'),
        ),
    ]
