# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0013_auto_20180510_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortTermForHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_unit_day', models.IntegerField(blank=True, null=True, verbose_name='Work Unit Day')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='month')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_hire', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
            ],
            options={
                'verbose_name': 'ShortTermForHire',
                'verbose_name_plural': 'ShortTermForHire',
            },
        ),
    ]
