# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-10 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0015_worktype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worktype',
            name='shortterm_for_hire',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_hire_work_type', to='basefarmers.ShortTermForHire', verbose_name='Shortterm For Hire'),
        ),
    ]
