# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0016_remove_lack_is_lack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basefarmer',
            name='lack',
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='lack',
            field=models.ManyToManyField(blank=True, null=True, to='basefarmers.Lack', verbose_name='Lack'),
        ),
    ]
