# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0016_auto_20180510_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worktype',
            name='work_type_code',
        ),
        migrations.AddField(
            model_name='worktype',
            name='work_type_code',
            field=models.ManyToManyField(blank=True, related_name='shortterm_hire_work_type_code', to='basefarmers.WorkTypeCode', verbose_name='Work Type Code'),
        ),
    ]
