# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0017_auto_20180504_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefarmer',
            name='annual_income',
            field=models.ManyToManyField(to='basefarmers.AnnualIncome', verbose_name='Annual Income'),
        ),
        migrations.AlterField(
            model_name='basefarmer',
            name='lack',
            field=models.ManyToManyField(to='basefarmers.Lack', verbose_name='Lack'),
        ),
    ]
