# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0018_auto_20180504_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmatch',
            name='basefarmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basefarmer', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
        migrations.AlterField(
            model_name='basefarmer',
            name='annual_income',
            field=models.ManyToManyField(blank=True, to='basefarmers.AnnualIncome', verbose_name='Annual Income'),
        ),
        migrations.AlterField(
            model_name='basefarmer',
            name='lack',
            field=models.ManyToManyField(blank=True, to='basefarmers.Lack', verbose_name='Lack'),
        ),
    ]
