# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0018_numberworkers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberworkers',
            name='AgeScope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='age_scope_number_workers', to='basefarmers.AgeScope', verbose_name='Age Scope'),
        ),
        migrations.AlterField(
            model_name='numberworkers',
            name='longterm_for_hire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_hire_number_workers', to='basefarmers.LongTermForHire', verbose_name='LongTerm For Hire'),
        ),
        migrations.AlterField(
            model_name='numberworkers',
            name='shortterm_for_hire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_hire_number_workers', to='basefarmers.ShortTermForHire', verbose_name='Shortterm For Hire'),
        ),
    ]
