# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0019_auto_20180504_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmatch',
            name='basefarmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basefarmer', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
    ]
