# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0019_auto_20180511_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoSalaryForHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='No Salary For Hire Month')),
                ('number_of_people', models.IntegerField(blank=True, null=True, verbose_name='Number Of People')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='no_salary_for_hire', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
            ],
            options={
                'verbose_name': 'NoSalaryForHire',
                'verbose_name_plural': 'NoSalaryForHire',
            },
        ),
        migrations.AlterField(
            model_name='longtermforhire',
            name='basefarmer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_for_hire', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
        migrations.AlterField(
            model_name='numberworkers',
            name='longterm_for_hire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_for_hire_number_workers', to='basefarmers.LongTermForHire', verbose_name='LongTerm For Hire'),
        ),
        migrations.AlterField(
            model_name='numberworkers',
            name='shortterm_for_hire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_for_hire_number_workers', to='basefarmers.ShortTermForHire', verbose_name='Shortterm For Hire'),
        ),
        migrations.AlterField(
            model_name='shorttermforhire',
            name='basefarmer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_for_hire', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='shortterm_for_hire',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_for_hire_work_type', to='basefarmers.ShortTermForHire', verbose_name='Shortterm For Hire'),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='work_type_code',
            field=models.ManyToManyField(blank=True, related_name='work_type_code', to='basefarmers.WorkTypeCode', verbose_name='Work Type Code'),
        ),
    ]
