# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0020_auto_20180511_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongTermForLack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(blank=True, null=True, verbose_name='Number Of People')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_for_lack', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
                ('work_type_code', models.ManyToManyField(blank=True, related_name='longterm_for_lack_work_type_code', to='basefarmers.WorkTypeCode', verbose_name='Work Type Code')),
            ],
            options={
                'verbose_name': 'LongTermForLack',
                'verbose_name_plural': 'LongTermForLack',
            },
        ),
        migrations.CreateModel(
            name='ShortTermForLack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_people', models.IntegerField(blank=True, null=True, verbose_name='Number Of People')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('basefarmer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_for_lack', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer')),
                ('product_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_for_lack_product_code', to='basefarmers.ProductCode', verbose_name='Product Code')),
                ('work_type_code', models.ManyToManyField(blank=True, related_name='shortterm_for_lack_work_type_code', to='basefarmers.WorkTypeCode', verbose_name='Work Type Code')),
            ],
            options={
                'verbose_name': 'ShortTermForLack',
                'verbose_name_plural': 'ShortTermForLack',
            },
        ),
    ]
