# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 05:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0021_longtermforlack_shorttermforlack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='longtermforlack',
            name='work_type_code',
        ),
        migrations.AddField(
            model_name='longtermforlack',
            name='work_type_code',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_for_lack_work_type_code', to='basefarmers.WorkTypeCode', verbose_name='Work Type Code'),
            preserve_default=False,
        ),
    ]
