# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-04 10:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0022_auto_20180504_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmatch',
            name='basefarmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basefarmer', to='basefarmers.BaseFarmer', verbose_name='BaseFarmer'),
            preserve_default=False,
        ),
    ]
