# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-11 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0022_auto_20180511_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='Months',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(blank=True, null=True, verbose_name='Month')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
                ('longterm_for_hire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_for_hire_months', to='basefarmers.LongTermForHire', verbose_name='LongTerm For Hire')),
                ('longterm_for_lack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='longterm_for_lack_months', to='basefarmers.LongTermForLack', verbose_name='Longterm For Lack')),
                ('shortterm_for_lack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shortterm_for_lack_months', to='basefarmers.ShortTermForLack', verbose_name='Shortterm For Lack')),
            ],
            options={
                'verbose_name': 'Months',
                'verbose_name_plural': 'Months',
            },
        ),
    ]
