# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0023_months'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerlandarea',
            name='farmer_land_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_land_type', to='basefarmers.FarmerLandType', verbose_name='Farmer Land Type'),
        ),
        migrations.AlterField(
            model_name='farmerlandarea',
            name='farmer_production_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='farmer_production_type', to='basefarmers.FarmerProductionType', verbose_name='Farmer Production Type'),
        ),
    ]
