# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-14 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0024_auto_20180514_1103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerlandtype',
            old_name='name',
            new_name='land_type_name',
        ),
        migrations.RemoveField(
            model_name='farmerlandarea',
            name='farmer_production_type',
        ),
        migrations.AddField(
            model_name='farmerlandtype',
            name='production_type_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Production Type Name'),
        ),
        migrations.DeleteModel(
            name='FarmerProductionType',
        ),
    ]
