# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0025_auto_20180514_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsHire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Is Hire Name')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'IsHire',
                'verbose_name_plural': 'IsHire',
            },
        ),
        migrations.AddField(
            model_name='basefarmer',
            name='is_hire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='is_hire', to='basefarmers.IsHire', verbose_name='Is Hire'),
        ),
    ]
