# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0027_auto_20180515_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsidy',
            name='application_content',
        ),
        migrations.AddField(
            model_name='subsidy',
            name='application_content',
            field=models.ManyToManyField(blank=True, null=True, related_name='application_content', to='basefarmers.ApplicationContent', verbose_name='ApplicationContent'),
        ),
    ]
