# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0028_auto_20180515_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lack',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Lack Name'),
        ),
    ]
