# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0030_auto_20180515_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomerangecode',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Income Range Code Name'),
        ),
        migrations.AlterField(
            model_name='lack',
            name='name',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Lack Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='markettype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Market Type Name'),
        ),
    ]
