# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0032_auto_20180515_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lack',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Lack Name'),
        ),
    ]
