# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-05-15 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basefarmers', '0033_auto_20180515_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basefarmer',
            name='lack',
            field=models.ManyToManyField(blank=True, null=True, to='basefarmers.Lack', verbose_name='Lack'),
        ),
    ]
